### ISSUE TITLE
Different infer sizes

### ISSUE THREAD

**Issue by omarcruzpantoja** [pdoublerainbow/bisenet-tensorflow#2]
Hi, I will assume we can't change the  "default infer size"? When I try I get shape matching errors. ( I would like to change it to W: 1242 H: 375

**Comment by pdoublerainbow** [comment]
Hi, the size should be divisible by 32.

**Comment by pdoublerainbow** [comment]
@omarcrz0   Hi, the size should be divisible by 32.

**Comment by omarcruzpantoja** [comment]
ahh yes, thanks it works
